services:
  - type: web
    name: emergency_QR
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn emergency_QR.wsgi:application"
    envVars:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: mysite
      #     property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4